export const RECEIVE_DECKS = 'RECEIVE_DECKS';
export const SELECT_DECK = 'SELECT_DECK';
export const RECEIVE_CARD = 'RECEIVE_CARD';

export const START_PLAY = 'START_PLAY';
export const FLIP_CARD = 'FLIP_CARD';
export const FINISH_PLAY = 'FINISH_PLAY';

export const RECEIVE_COURSES = 'RECEIVE_COURSES';
export const SELECT_COURSE = 'SELECT_COURSE';
export const ADD_COURSE = 'ADD_COURSE';

export const RECEIVE_STUDENT_DECKS = 'RECEIVE_STUDENT_DECKS';
export const SELECT_STUDENT_DECK = 'SELECT_STUDENT_DECK';

export const RECEIVE_STUDENTS = 'RECEIVE_STUDENTS';
export const ADD_STUDENT = 'ADD_STUDENT';

export const SIGN_IN = 'SIGN_IN';
export const SIGN_OUT = 'SIGN_OUT';

export const ERR_FAILED_REQUEST = 'ERR_FAILED_REQUEST';

